	//foods for autocomplete
	var foodsENG = ["Lamb","Beef fillet","Geese","The hen","Wiener","Lukanka","Sheep","Loops",
	"Chicken wings","Butte chicken","Chicken breast meat","Chicken shoulder meat","Butte turkey meat",
	"Breast turkey meat","Beef turkey meat","Salam Kamchia","Butte pork","Pork loin",
	"Pork fillet - rib arc","Butte veal","Beef neck","Shoulder beef","Veal meat","Beef fillet",
	"Hamburg salami","Larded salami","Goose egg","An egg is a hen","Egg - turkey",
	"Egg protein - chickens","Egg yolk - chickens","White Cupid",
	"Whitefish","Kalkan","Karagoz","Mullet","Fennel","Lavrak","Lefer","Merlot","Omar",
	"Palamud","Trout","Tuna fish","Sardine","Safrid","Mackerel","Som","Salmon",
	"Trizona","Shark fillet","Caviar salmon","Caviar carp","Heck","Herring","Tzatz","Chiga",
	"Carp","Pike","Activia","The curd is defatted","Cheese cows",
	"Cheese sheep","Yoghurt","Yoghurt","Yoghurt","Cheese","Sheep cheese","Milk","Milk","Milk",
	"Sheep's milk","Cream","Boiled pretzel","Viennese muffin",
	"Rye","Cheese","Easter bread","Lentils","Macaroni and spaghetti","Oat bran","Oat flakes",
	"White rice","Brown rice","Millet","Wheat","Wheat bran","Rye","Soybeans","Rusks","Tutmanik",
	"Beans","Bonus Bread Rye","Vita bread without flour","Bread white","Rye bread",
	"Maize","Vegetables","Artichoke","Asparagus","Broccoli","Brussels sprouts","Peas","Mushrooms",
	"Tomatoes","Cabbage","Chinese cabbage","Red cabbage","Cambi","Potatoes","Cauliflower",
	"Sour cabbage","Cucumbers","Green onions","Onion pg","Lettuce","Carrots","Eggplant",
	"Radish","Turnip","Spinach","Pumpkin","Zucchini","Green beans","Beetroot red","Pepper",
	"Fruits and nuts","Avocado","Pineapple","Almonds roasted","Almonds are harsh","Bananas",
	"Cherries","Grapefruit","White grape","Pink grapes","Red grapes","Watermelon","Julie",
	"Apricots","Kiwi","Pears","Linseed","Hazelnuts","Lemons","Mango","Mandarins","Marmalade",
	"Born","Walnuts","Pomelo","Oranges","Peaches","Melon","Plums blue","Sunflower","Figs",
	"Raisins","Dried apricots","Dried plums","Dried figs","Pumpkin","Pumpkin seeds","Tuyere",
	"Peanuts","Cherries","Apples","Berries","Language","Sugar","Olive oil","Butter","Wheat sprouts",
	"Margarine","Green Olives","Jumbo Olives","Olives","Avocado oil","Almond oil","Cocoa butter",
	"Coconut oil","Oats","Sesame oil","Honey","Brain","Sunflower oil","Soybean Oil","Bacon",
	"Chicken hearts","Liver","Sweets","Sweet + cookies","Everest biscuits nuts",
	"Breakfast Biscuits - Cocoa","Breakfast Cookies Win","Coffee Biscuits",
	"Oatmeal cookies with oatmeal","Trajan cookies","Morena waffle","Motto waffle",
	"Simona waffle","Spoko Waffle","Troy Waffle","Seagull Waffle","Dark Chokolate Chocolate Svog",
	"Lindt% Cocoa Chocolate","Lindt Orange Dark Chocolate","Milka Cream Chocolate",
	"Milka chocolate with whole hazelnuts"];

	var foodsBG = ["Агнешко","Говеждо месо от филе","Гъски","Кокоше","Кренвирш","Луканка","Овче",
	"Петли","Пилешки крила","Пилешко месо от бут","Пилешко месо от гърди","Пилешко месо от плешка",
	"Пуешко месо от бут","Пуешко месо от гърди","Пуешко месо от плешка","Саздърма","Салам Камчия",
	"Свинско месо от бут","Свинско филе","Свинско филе - ребрена дъга","Телешко месо от бут",
	"Телешко месо от врат","Телешко месо от плешка","Телешко месо от подбедрица","Телешко филе",
	"Хамбургски салам","Шпеков салам","Яйце - гъше","Яйце - кокоше","Яйце - пуешко","Яйчен белтък - кокоши",
	"Яйчен жалтък - кокоши","Бял амур","Бяла риба","Калкан","Карагьоз","Кефал",
	"Копърка","Лаврак","Лефер","Мерлуза","Омар","Паламуд","Пъстърва","Риба тон","Сардина","Сафрид",
	"Скумрия","Сом","Сьомга","Трицона","Филе от акула","Хайвер-сьомга",
	"Хайвер-шаран","Хек","Херинга","Цаца","Чига","Шаран","Щука","Активиа",
	"Извара обезмаслена","Кашкавал краве","Кашкавал овчи","Кисело мляко","Кисело мляко","Кисело мляко",
	"Краве сирене","Овче сирене","Прясно мляко","Прясно мляко","Прясно мляко","Прясно мляко Овче",
	"Сметана","Хлебни изделия и зърнени храни","Варен геврек","Виенска кифла","Жито","Кашкавалка",
	"Козунак","Леща","Макарони и спагети","Овесени трици","Овесени ядки","Бял ориз","Кафяв ориз",
	"Просо","Пшеница","Пшенични трици","Ръж","Соя","Сухари","Тутманик","Фасул","Хляб", "Ръжен Хляб",
	"Хляб бял","Хляб ръжен","Хляб типов","Царевица","Зеленчуци","Артишок","Аспержи","Броколи",
	"Брюкселско зеле","Грах","Гъби","Домати","Зеле","Китайско зеле","Червено зеле","Камби","Картофи",
	"Карфиол","Кисело зеле","Краставици","Лук зелен","Лук стар","Маруля","Моркови","Патладжан",
	"Репички","Ряпа","Спанак","Тиква","Тиквички","Фасул зелен","Цвекло червено","Чушка",
	"Плодове и ядки","Авокадо","Ананас","Бадеми печени","Бадеми сурови","Банани","Вишни","Грейпфрут",
	"Бяло грозде","Розово грозде ","Червено грозде","Диня","Дюли","Кайсии","Киви","Круши","Ленено семе",
	"Лешници","Лимони","Манго","Мандарини","Мармалади","Нар","Орехи","Помело","Портокали","Праскови",
	"Пъпеш","Сливи сини","Слънчоглед","Смокини","Стафиди","Сушени кайсии","Сушени сливи","Сушени смокини",
	"Тиква","Тиквени семки","Фурми","Фъстъци","Череши","Ябалки","Ягоди","Език","Захар","Зехтин",
	"Краве масло","Кълнове от пшеница","Маргарин","Зелени Маслини","Джъмбо Маслини ","Маслини",
	"Масло от Авокадо","Масло от Бадем","Масло от Какао","Масло от Кокос","Масло от Овес","Масло от Сусам",
	"Мед","Мозък","Слънчогледово Олио","Соево Олио","Сланина","Пилешки Сърца","Черен дроб","Захарни изделия",
	"Бисквити Sweet+","Бисквити Еверест","ореховки","Бисквити Траяна","Шоколад Dark Chokolate",
	"Шоколад Lindt % cocoa","Шоколад Lindt Orange Dark","Шоколад Milka Cream",
	"Шоколад Milka с цели лешници","Кока кола"];